plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.hsnsn.actiontemplate'
    compileSdk 35

    defaultConfig {
        applicationId 'com.hsnsn.actiontemplate'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.2.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'androidx.credentials:credentials:1.5.0'
    implementation 'androidx.credentials:credentials-play-services-auth:1.5.0'
    implementation 'com.google.android.libraries.identity.googleid:googleid:1.1.1'
}
